version: "3.9"

services:
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - ./Backend/.env
    labels:
      author: "Ujjwal Saini"
    depends_on:
      mongo:
        condition: service_healthy
    networks:
      - investiq-net
    restart: unless-stopped
    command: ["node", "dist/index.js"]

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    env_file:
      - ./Frontend/.env
    labels:
      author: "Ujjwal Saini"
    networks:
      - investiq-net
    restart: unless-stopped
    command: ["pnpm", "run", "build"]

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    labels:
      author: "Ujjwal Saini"
    networks:
      - investiq-net
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  workflows:
    build:
      context: ./workflows
      dockerfile: Dockerfile
    container_name: workflows
    environment:
      - PORT=4000
    ports:
      - "4000:4000"
    labels:
      author: "Ujjwal Saini"
    networks:
      - investiq-net
    restart: unless-stopped
    depends_on:
      - backend
    command: ["pnpm", "start"]

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"
    depends_on:
      - backend
      - workflows
    networks:
      - investiq-net
    restart: unless-stopped

volumes:
  mongo_data:

networks:
  investiq-net:
    driver: bridge

labels:
  author: "Ujjwal Saini, Gayatri Singh"
